### ISSUE TITLE
File "setup.py", line 13, in <module>

### ISSUE THREAD

**Issue by y0d4a** [pmsosa/duckhunt#3]
when try to make exe from it, i got dll load failed.

`running py2exe
*** searching for required modules ***
*** parsing results ***
*** finding dlls needed ***
Traceback (most recent call last):
  File "setup.py", line 13, in <module>
    zipfile = None,
  File "c:\Python27\lib\distutils\core.py", line 152, in setup
    dist.run_commands()
  File "c:\Python27\lib\distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "c:\Python27\lib\distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "c:\Python27\lib\site-packages\py2exe\build_exe.py", line 243, in run
    self._run()
  File "c:\Python27\lib\site-packages\py2exe\build_exe.py", line 305, in _run
    dlls = self.find_dlls(extensions)
  File "c:\Python27\lib\site-packages\py2exe\build_exe.py", line 389, in find_dlls
    self.dll_excludes)
  File "c:\Python27\lib\site-packages\py2exe\build_exe.py", line 1021, in find_dependend_dlls
    import py2exe_util
ImportError: DLL load failed: %1 is not a valid Win32 `application.``

where i am wrong? :)

**Comment by pmsosa** [comment]
Hmm that is a problem directly with Py2exe. Have you tried: 
- https://stackoverflow.com/questions/19019720/importerror-dll-load-failed-1-is-not-a-valid-win32-application-but-the-dlls#19042026

**Comment by y0d4a** [comment]
ah yes... seems like, i just try simple hello word and it is the same...
I will now look on other side, when i found solution i will post it.
Thank you!

**Comment by y0d4a** [comment]
So, after installing python2.7 and others requirements for all users for 32bit architecture, all pass fine!

here are the files:
https://www.python.org/ftp/python/2.7/python-2.7.msi
https://github.com/mhammond/pywin32/releases/download/b224/pywin32-224.win32-py2.7.exe
https://sourceforge.net/projects/pyhook/files/pyhook/1.5.1/pyHook-1.5.1.win32-py2.7.exe/download
https://sourceforge.net/projects/py2exe/files/py2exe/0.6.9/py2exe-0.6.9.win32-py2.7.exe/download

after install, set the PATH for python2.7 and inside folder where is script:
python setup.py install
